# Generated by Django 5.2 on 2025-05-06 13:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ChaiVarity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("image", models.ImageField(upload_to="myapp1/")),
                ("date_added", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "chai_type",
                    models.CharField(
                        choices=[
                            ("BL", "Black Tea"),
                            ("GR", "Green Tea"),
                            ("WT", "White Tea"),
                        ],
                        max_length=2,
                    ),
                ),
            ],
        ),
    ]
