# Generated by Django 5.2 on 2025-05-17 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "emp_id",
                    models.CharField(max_length=10, primary_key=True, serialize=False),
                ),
                ("emp_name", models.CharField(max_length=30)),
                ("emp_designation", models.CharField(max_length=20)),
            ],
        ),
    ]
